{{- if and .Values.secret.enabled .Values.secret.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "microservice.fullname" . }}-external-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.secret.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secret.externalSecret.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ include "microservice.fullname" . }}-external-secret
    creationPolicy: Owner
  data:
  {{- range .Values.secret.externalSecret.data }}
  - secretKey: {{ .secretKey }}
    remoteRef:
      key: {{ .remoteRef.key }}
  {{- end }}
{{- end }}
