{{- if .Values.nginxConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "microservice.fullname" . }}-nginx
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
data:
  nginx.conf: |
{{ .Values.nginxConfig | indent 4 }}
{{- end }}
