{{- if .Values.secret.externalSecret.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.secret.externalSecret.secretStoreName | default "gcpsm-secret-store" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.googleProjectId | default "ai-agency-479516" }}
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: {{ include "microservice.serviceAccountName" . }}
          clusterLocation: {{ .Values.googleClusterLocation | default "us-central1" }}
          clusterName: {{ .Values.googleClusterName | default "gke-autopilot-cluster" }}
{{- end }}
