apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "microservice.fullname" . }}-snowflake-migrations
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
data:
{{- $root := . -}}
{{- range $path, $_ := .Files.Glob "migrations/*" }}
  {{ base $path }}: |
{{ $root.Files.Get $path | indent 4 }}
{{- end }}
